# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 08:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u680f\u76ee\u540d\u79f0')),
                ('link', models.CharField(db_index=True, max_length=256, verbose_name='\u680f\u76ee\u94fe\u63a5')),
                ('intro', models.TextField(default='', verbose_name='\u680f\u76ee\u7b80\u4ecb')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u680f\u76ee',
                'verbose_name_plural': '\u680f\u76ee',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u6587\u7ae0', 'verbose_name_plural': '\u6587\u7ae0'},
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='\u5185\u5bb9'),
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(db_index=True, default=datetime.datetime(2017, 1, 23, 8, 59, 16, 127000, tzinfo=utc), max_length=256, verbose_name='\u6587\u7ae0\u94fe\u63a5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True, verbose_name='\u6b63\u5f0f\u53d1\u5e03'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=256, verbose_name='\u6587\u7ae0\u6807\u9898'),
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ManyToManyField(to='article.Column', verbose_name='\u5f52\u5c5e\u680f\u76ee'),
        ),
    ]
