# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 09:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170123_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
        migrations.AddField(
            model_name='article',
            name='pub_time',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 1, 23, 9, 16, 28, 273000, tzinfo=utc), verbose_name='\u53d1\u5e03\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='update_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
