# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u5927\u5b66\u540d\u79f0')),
                ('hero', models.FileField(upload_to='./branch/hero-image-files/', verbose_name='\u80cc\u666f\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u5206\u90e8',
                'verbose_name_plural': '\u5206\u90e8\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='FriendlyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u6807\u9898')),
                ('link', models.TextField(default='', verbose_name='\u94fe\u63a5')),
                ('image', models.FileField(upload_to='./branch/friendly-link-image-files/', verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u53cb\u60c5\u94fe\u63a5',
                'verbose_name_plural': '\u53cb\u60c5\u94fe\u63a5',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='titleImage',
            field=models.FileField(blank=True, null=True, upload_to='./branch/article-title-images/', verbose_name='\u4e3b\u9898\u56fe\u7247'),
        ),
    ]
