# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20170211_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-update_time'], 'verbose_name': '\u6587\u7ae0', 'verbose_name_plural': '\u53d1\u5e03\u6587\u7ae0'},
        ),
    ]
