# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0004_post_postreplie'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', verbose_name='\u5185\u5bb9')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Post', verbose_name='\u56de\u590d')),
            ],
            options={
                'ordering': ['-pub_time'],
                'verbose_name': '\u56de\u5e16',
                'verbose_name_plural': '\u56de\u5e16',
            },
        ),
        migrations.RemoveField(
            model_name='postreplie',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postreplie',
            name='to',
        ),
        migrations.DeleteModel(
            name='PostReplie',
        ),
    ]
