# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 10:43
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_auto_20170213_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u5185\u5bb9'),
        ),
    ]
