# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0008_auto_20170217_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u6807\u9898')),
                ('link', models.TextField(default='', verbose_name='\u94fe\u63a5')),
                ('image', models.FileField(upload_to='./branch/tools-image-files/', verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u5c0f\u52a9\u624b',
                'verbose_name_plural': '\u5b9e\u7528\u5c0f\u52a9\u624b',
            },
        ),
    ]
