# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0009_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=' ', max_length=256, verbose_name='\u6807\u9898'),
        ),
    ]
