# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticTeammates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thePersonName', models.CharField(max_length=256, verbose_name='\u540d\u5b57')),
                ('thePersonIntro', models.TextField(default='', verbose_name='\u7b80\u4ecb')),
                ('theHeaderFileName', models.CharField(max_length=256, verbose_name='\u5934\u50cf\u6587\u4ef6\u540d')),
            ],
            options={
                'verbose_name': '\u56e2\u961f\u6210\u5458',
                'verbose_name_plural': '\u56e2\u961f\u6210\u5458\u4fe1\u606f',
            },
        ),
    ]
