# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_staticteammates'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='thePartners',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='theSigners',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='theVisits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
