# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_auto_20170128_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theHref', models.CharField(max_length=256, verbose_name='\u56fe\u7247\u6587\u4ef6\u540d')),
                ('theLink', models.TextField(default='', verbose_name='\u8d85\u94fe\u63a5')),
            ],
            options={
                'verbose_name': '\u8f6e\u64ad\u56fe\u7247',
                'verbose_name_plural': '\u8f6e\u64ad\u56fe\u7247\u7684\u94fe\u63a5\u548c\u6587\u4ef6\u540d',
            },
        ),
    ]
