# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0005_staticinfo_thenotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimages',
            name='theImage',
            field=models.FileField(default=0, upload_to='./header/'),
            preserve_default=False,
        ),
    ]
