# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0007_auto_20170129_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticteammates',
            name='theHeaderFileName',
        ),
        migrations.AddField(
            model_name='staticteammates',
            name='theHeaderImage',
            field=models.FileField(default=0, upload_to='./header/', verbose_name='\u4e0a\u4f20\u5934\u50cf'),
            preserve_default=False,
        ),
    ]
