# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0008_auto_20170129_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimages',
            name='theImage',
            field=models.FileField(upload_to='./page1-hero-image-files/', verbose_name='\u4e0a\u4f20\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='staticteammates',
            name='theHeaderImage',
            field=models.FileField(upload_to='./page1-header-image-files/', verbose_name='\u4e0a\u4f20\u5934\u50cf'),
        ),
    ]
