# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0009_auto_20170129_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticinfo',
            name='theNotice',
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='thePartners',
            field=models.IntegerField(verbose_name='\u5408\u4f5c\u4f19\u4f34\u6570'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='theSigners',
            field=models.IntegerField(verbose_name='\u6ce8\u518c\u91cf'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='theVisits',
            field=models.IntegerField(verbose_name='\u8bbf\u95ee\u91cf'),
        ),
    ]
