# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0011_auto_20170129_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='theLogo',
            field=models.FileField(default=0, upload_to='./page1-logo-file/', verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
