# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0012_staticinfo_thelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page1Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theTitle', models.CharField(max_length=256, unique=True, verbose_name='\u6807\u9898')),
                ('OGG', models.FileField(upload_to='./page1-video-files/', verbose_name='ogg')),
                ('MP4', models.FileField(upload_to='./page1-video-files/', verbose_name='mp4')),
                ('WEBM', models.FileField(upload_to='./page1-video-files/', verbose_name='webm')),
                ('SWF', models.FileField(upload_to='./page1-video-files/', verbose_name='swf')),
            ],
            options={
                'verbose_name': '\u5ba3\u4f20\u89c6\u9891',
                'verbose_name_plural': '\u5ba3\u4f20\u89c6\u9891',
            },
        ),
    ]
