# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0013_page1video'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='theLink',
            field=models.CharField(default=0, max_length=256, verbose_name='\u672c\u7ad9\u7f51\u5740'),
            preserve_default=False,
        ),
    ]
