# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0014_staticinfo_thelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimages',
            name='theImage',
            field=models.FileField(upload_to='./central/hero-image-files/', verbose_name='\u4e0a\u4f20\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='page1video',
            name='MP4',
            field=models.FileField(upload_to='./central/video-files/', verbose_name='mp4'),
        ),
        migrations.AlterField(
            model_name='page1video',
            name='OGG',
            field=models.FileField(upload_to='./central/video-files/', verbose_name='ogg'),
        ),
        migrations.AlterField(
            model_name='page1video',
            name='SWF',
            field=models.FileField(upload_to='./central/video-files/', verbose_name='swf'),
        ),
        migrations.AlterField(
            model_name='page1video',
            name='WEBM',
            field=models.FileField(upload_to='./central/video-files/', verbose_name='webm'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='theLogo',
            field=models.FileField(upload_to='./central/logo-file/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='staticteammates',
            name='theHeaderImage',
            field=models.FileField(upload_to='./central/header-image-files/', verbose_name='\u4e0a\u4f20\u5934\u50cf'),
        ),
    ]
