# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0015_auto_20170131_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticteammates',
            name='theRemark',
            field=models.CharField(default='normal', max_length=256, verbose_name='\u804c\u4f4d\u5907\u6ce8'),
        ),
    ]
