# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0016_staticteammates_theremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theTitle', models.CharField(max_length=256, unique=True, verbose_name='\u6807\u9898')),
                ('theContent', models.TextField(default='', verbose_name='\u5185\u5bb9')),
                ('theImage', models.FileField(upload_to='./central/about-image-files/', verbose_name='\u5c01\u9762')),
            ],
            options={
                'verbose_name': '\u7f51\u7ad9\u7b80\u4ecb\u4e0e\u56e2\u961f\u6210\u5458',
                'verbose_name_plural': '\u7f51\u7ad9\u7b80\u4ecb\u4e0e\u56e2\u961f\u6210\u5458',
            },
        ),
        migrations.DeleteModel(
            name='StaticTeammates',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='theIntro',
        ),
    ]
