# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0018_auto_20170213_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='\u540d\u79f0')),
                ('link', models.CharField(max_length=256, verbose_name='\u5206\u90e8\u7f51\u5740')),
            ],
            options={
                'verbose_name': '\u9ad8\u6821\u5217\u8868',
                'verbose_name_plural': '\u9ad8\u6821\u5217\u8868',
            },
        ),
    ]
