# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0019_branchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchlist',
            name='logo',
            field=models.FileField(default=0, upload_to='./central/branchs-logo-image-files/', verbose_name='\u6821\u5fbd'),
            preserve_default=False,
        ),
    ]
