# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0021_staticabout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticabout',
            name='name',
            field=models.CharField(max_length=256, verbose_name='\u94fe\u63a5(\u4e0d\u8981\u4fee\u6539)'),
        ),
    ]
