# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0023_remove_staticabout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticabout',
            name='name',
            field=models.CharField(default=0, max_length=256, verbose_name='\u94fe\u63a5(\u4e0d\u8981\u4fee\u6539)'),
            preserve_default=False,
        ),
    ]
