# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 06:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('central', '0027_staticabout_thename'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='central.BranchList', verbose_name='\u5b66\u6821')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u9ad8\u6821\u5217\u8868',
                'verbose_name_plural': '\u9ad8\u6821\u5217\u8868',
            },
        ),
    ]
