# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 07:22
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('central', '0029_auto_20170218_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u6807\u9898')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u5185\u5bb9')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('published', models.BooleanField(default=True, verbose_name='\u6b63\u5f0f\u53d1\u5e03')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'ordering': ['-update_time'],
                'verbose_name': '\u9ad8\u6821\u52a8\u6001',
                'verbose_name_plural': '\u53d1\u5e03\u52a8\u6001',
            },
        ),
        migrations.AlterModelOptions(
            name='staticabout',
            options={'verbose_name': '\u7f51\u7ad9\u7b80\u4ecb\u3001\u56e2\u961f\u6210\u5458\u4e0e\u8054\u7cfb\u65b9\u5f0f', 'verbose_name_plural': '\u5173\u4e8e\u672c\u7ad9'},
        ),
    ]
